<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<OutputType>Library</OutputType>
		<SolutionDir Condition="$(SolutionDir) == '' Or $(SolutionDir) == '*Undefined*'">..\</SolutionDir>
		<Nullable>enable</Nullable>
		<AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
		<AppendRuntimeIdentifierToOutputPath>false</AppendRuntimeIdentifierToOutputPath>
		<Platforms>AnyCPU;x64</Platforms>
	</PropertyGroup>
	<PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
		<OutputPath>..\Output\Debug\</OutputPath>
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
	</PropertyGroup>
	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|x64'">
		<OutputPath>..\Output\Debug\</OutputPath>
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
	</PropertyGroup>
	<PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|AnyCPU' ">
		<OutputPath>..\Output\Release\</OutputPath>
	</PropertyGroup>
	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|x64'">
		<OutputPath>..\Output\Release\</OutputPath>
	</PropertyGroup>
	<ItemGroup>
		<ProjectReference Include="..\Wox.Plugin\Wox.Plugin.csproj" />
	</ItemGroup>
	<ItemGroup>
		<Folder Include="UI\" />
	</ItemGroup>
	<ItemGroup>
	  <PackageReference Include="ToolGood.Words.FirstPinyin" Version="3.1.0.3" />
	</ItemGroup>
	<PropertyGroup />
</Project>